// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/lupguo/linkstash/app/application"
	"github.com/lupguo/linkstash/app/domain/services"
	"github.com/lupguo/linkstash/app/handler"
	"github.com/lupguo/linkstash/app/infra/config"
	"github.com/lupguo/linkstash/app/infra/db"
	"github.com/lupguo/linkstash/app/infra/llm"
	"github.com/lupguo/linkstash/app/infra/search"
)

// InitializeApp creates a fully wired App instance.
func InitializeApp(confPath string) (*App, error) {
	// Infra
	cfg, err := config.Load(confPath)
	if err != nil {
		return nil, err
	}

	database, err := db.InitDB(&cfg.Database)
	if err != nil {
		return nil, err
	}

	llmClient := llm.NewLLMClient(cfg.LLM.Chat, cfg.LLM.Embedding)

	keywordSearch := search.NewKeywordSearch(database)

	// Repos
	urlRepo := db.NewURLRepoImpl(database)
	visitRepo := db.NewVisitRepoImpl(database)
	llmLogRepo := db.NewLLMLogRepoImpl(database)
	embeddingRepo := db.NewEmbeddingRepoImpl(database)
	shortURLRepo := db.NewShortURLRepoImpl(database)

	// Vector search (depends on embeddingRepo)
	vectorSearch := search.NewVectorSearch(embeddingRepo)
	if err := vectorSearch.LoadAll(); err != nil {
		println("[Warning] Failed to load embeddings cache:", err.Error())
	}

	// Services
	urlService := services.NewURLService(urlRepo)
	workerService := services.NewWorkerService(urlRepo, llmLogRepo, embeddingRepo, llmClient, cfg.LLM.Prompts)
	searchService := services.NewSearchService(keywordSearch, vectorSearch, llmClient)
	shortURLService := services.NewShortURLService(shortURLRepo)
	visitService := services.NewVisitService(visitRepo)

	// Usecases
	urlUsecase := application.NewURLUsecase(urlService)
	analysisUsecase := application.NewAnalysisUsecase(workerService)
	searchUsecase := application.NewSearchUsecase(searchService, urlRepo)
	shortURLUsecase := application.NewShortURLUsecase(shortURLService)

	// Handlers
	authCfg := &cfg.Auth
	authHandler := handler.NewAuthHandler(authCfg)
	urlHandler := handler.NewURLHandler(urlUsecase)
	searchHandler := handler.NewSearchHandler(searchUsecase)
	shortURLHandler := handler.NewShortURLHandler(shortURLUsecase)
	webHandler := handler.NewWebHandler(urlUsecase, searchUsecase, authCfg, "web")

	app := &App{
		Config:          cfg,
		AuthHandler:     authHandler,
		URLHandler:      urlHandler,
		SearchHandler:   searchHandler,
		ShortURLHandler: shortURLHandler,
		WebHandler:      webHandler,
		AnalysisUsecase: analysisUsecase,
		VisitService:    visitService,
	}
	return app, nil
}
